# Generated by Django 3.2 on 2021-07-21 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_title', models.CharField(max_length=30)),
                ('awarded_by', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=30)),
                ('university', models.CharField(max_length=30)),
                ('faculty', models.CharField(max_length=30)),
                ('institute', models.CharField(max_length=30)),
                ('year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('institute', models.CharField(max_length=30)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField()),
                ('instagram', models.URLField()),
                ('linkedin', models.URLField()),
                ('twitter', models.URLField()),
                ('youtube', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('biography', models.TextField()),
                ('practice_area', models.CharField(max_length=30)),
                ('legal_fees', models.IntegerField(blank=True, default=15)),
                ('publication', models.TextField()),
                ('status', models.CharField(choices=[('approved', 'approved'), ('rejected', 'rejected')], max_length=20)),
                ('professional_associations', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='profile/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wakil.awards')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wakil.experience')),
                ('links', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wakil.link')),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
