# Generated by Django 3.2 on 2021-07-06 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='askLawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=10)),
                ('address', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.CharField(choices=[('Edit', 'Edit'), ('View', 'View'), ('Delete', 'Delete')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='askuser',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='askuser',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='answer',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('options', models.CharField(choices=[('Edit', 'Edit'), ('View', 'View'), ('Delete', 'Delete')], max_length=20)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.askuser')),
            ],
        ),
    ]
