# Generated by Django 3.2 on 2021-07-15 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210715_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='options',
        ),
        migrations.RemoveField(
            model_name='points',
            name='correct',
        ),
    ]
