# Generated by Django 3.2 on 2021-07-15 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_points_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='points',
            old_name='points',
            new_name='stars',
        ),
        migrations.RemoveField(
            model_name='points',
            name='created_date',
        ),
    ]
