# Generated by Django 3.2 on 2021-07-28 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210715_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsAllocated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_choice', models.CharField(choices=[('registration', 'registration'), ('question', 'question'), ('answer', 'answer')], max_length=20)),
                ('point', models.IntegerField(default=15)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='points',
            old_name='stars',
            new_name='points_earned',
        ),
        migrations.RemoveField(
            model_name='points',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='options',
        ),
        migrations.AddField(
            model_name='points',
            name='points_title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.pointsallocated'),
            preserve_default=False,
        ),
    ]
