# Generated by Django 3.2 on 2021-07-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forum',
            old_name='date_created',
            new_name='created_date',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='link',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='name',
        ),
        migrations.AddField(
            model_name='forum',
            name='full_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discussion',
            name='discuss',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='forum',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='forum',
            name='topic',
            field=models.CharField(max_length=100),
        ),
    ]
