# Generated by Django 3.2 on 2021-07-09 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210708_1233'),
        ('Forum', '0002_auto_20210708_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.asklawyer'),
            preserve_default=False,
        ),
    ]
