# Generated by Django 3.2 on 2021-07-15 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0003_discussion_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='email',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='full_name',
        ),
    ]
